### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by kyw-iduce** [augustjune/context-applied#4]
Thank you for great plugins, but for some reason I am unable to use it. I get error message: 
s <- F.read //cannot resolve symbol F

Do you have a working sample toy example?

Regards

**Comment by augustjune** [comment]
Hi @kyw-iduce 
It seems like you're trying to compile the code inside IntelliJ IDEA.
Intellij uses its own compiler that sometimes marks valid code as incorrect.
At the moment, you should try to compile the code with your build tool (e.g. sbt) instead of IntelliJ.
Alternatively, you can consider using [metals](https://scalameta.org/metals/) with your IDE, since it uses [bloop](https://scalacenter.github.io/bloop/) for code compilation.

All examples from README are valid and you can use them in order to get familiar with the plugin.
In some of them, I refer to such type classes as `Applicative` or `Monad` which you can find in [cats](https://github.com/typelevel/cats) library.
